/*
SQLyog Community v13.1.5  (64 bit)
MySQL - 10.4.13-MariaDB 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;


insert into `prp_menu` (`id`, `menutype`, `title`, `alias`, `note`, `path`, `link`, `type`, `published`, `parent_id`, `level`, `component_id`, `checked_out`, `checked_out_time`, `browserNav`, `access`, `img`, `template_style_id`, `params`, `lft`, `rgt`, `home`, `language`, `client_id`) values('410','main','COM_CATPROMOCIONAL_MMATRICES','com-catpromocional-mmatrices','','com-catpromocional-mcatalogo/com-catpromocional-mmatrizvariables','index.php?option=com_catpromocional&view=catcosproductos','component','1','1','1','10049','0','0000-00-00 00:00:00','0','1','class:component','0','{}','203','240','0','','1');
insert into `prp_menu` (`id`, `menutype`, `title`, `alias`, `note`, `path`, `link`, `type`, `published`, `parent_id`, `level`, `component_id`, `checked_out`, `checked_out_time`, `browserNav`, `access`, `img`, `template_style_id`, `params`, `lft`, `rgt`, `home`, `language`, `client_id`) values('411','main','COM_CATPROMOCIONAL_MMATRIZ_ATRIBUTOS','com-catpromocional-mmatrizatributos','','com-catpromocional-mcatalogo/com-catpromocional-mmatrizatributos','index.php?option=com_catpromocional&view=catmtzatributos','component','1','410','2','10049','0','0000-00-00 00:00:00','0','1','class:component','0','{}','240','241','0','','1');
insert into `prp_menu` (`id`, `menutype`, `title`, `alias`, `note`, `path`, `link`, `type`, `published`, `parent_id`, `level`, `component_id`, `checked_out`, `checked_out_time`, `browserNav`, `access`, `img`, `template_style_id`, `params`, `lft`, `rgt`, `home`, `language`, `client_id`) values('412','main','COM_CATPROMOCIONAL_MMATRIZ_CATEGORIAS','com-catpromocional-mmatrizcategorias','','com-catpromocional-mcatalogo/com-catpromocional-mmatrizcategorias','index.php?option=com_catpromocional&view=catmtzcategorias','component','1','410','2','10049','0','0000-00-00 00:00:00','0','1','class:component','0','{}','240','241','0','','1');
insert into `prp_menu` (`id`, `menutype`, `title`, `alias`, `note`, `path`, `link`, `type`, `published`, `parent_id`, `level`, `component_id`, `checked_out`, `checked_out_time`, `browserNav`, `access`, `img`, `template_style_id`, `params`, `lft`, `rgt`, `home`, `language`, `client_id`) values('413','main','COM_CATPROMOCIONAL_MMATRIZ_CORRESPONDENCIA','com-catpromocional-mmatrizcorrespondencias','','com-catpromocional-mcatalogo/com-catpromocional-mmatrizcorrespondencias','index.php?option=com_catpromocional&view=catmtzcorrespondecia','component','1','410','2','10049','0','0000-00-00 00:00:00','0','1','class:component','0','{}','240','241','0','','1');
insert into `prp_menu` (`id`, `menutype`, `title`, `alias`, `note`, `path`, `link`, `type`, `published`, `parent_id`, `level`, `component_id`, `checked_out`, `checked_out_time`, `browserNav`, `access`, `img`, `template_style_id`, `params`, `lft`, `rgt`, `home`, `language`, `client_id`) values('414','main','COM_CATPROMOCIONAL_MMATRIZ_FORMULAS','com-catpromocional-mmatrizformulas','','com-catpromocional-mcatalogo/com-catpromocional-mmatrizformulas','index.php?option=com_catpromocional&view=catmtzformulas','component','1','410','2','10049','0','0000-00-00 00:00:00','0','1','class:component','0','{}','240','241','0','','1');
insert into `prp_menu` (`id`, `menutype`, `title`, `alias`, `note`, `path`, `link`, `type`, `published`, `parent_id`, `level`, `component_id`, `checked_out`, `checked_out_time`, `browserNav`, `access`, `img`, `template_style_id`, `params`, `lft`, `rgt`, `home`, `language`, `client_id`) values('415','main','COM_CATPROMOCIONAL_MMATRIZ_TECNICAS','com-catpromocional-mmatriztecnicas','','com-catpromocional-mcatalogo/com-catpromocional-mmatriztecnicas','index.php?option=com_catpromocional&view=catmtztecnicas','component','1','410','2','10049','0','0000-00-00 00:00:00','0','1','class:component','0','{}','240','241','0','','1');
insert into `prp_menu` (`id`, `menutype`, `title`, `alias`, `note`, `path`, `link`, `type`, `published`, `parent_id`, `level`, `component_id`, `checked_out`, `checked_out_time`, `browserNav`, `access`, `img`, `template_style_id`, `params`, `lft`, `rgt`, `home`, `language`, `client_id`) values('416','main','COM_CATPROMOCIONAL_MMATRIZ_UNIFICACION','com-catpromocional-mmatrizunificacion','','com-catpromocional-mcatalogo/com-catpromocional-mmatrizunificacion','index.php?option=com_catpromocional&view=catmtzunificacion','component','1','410','2','10049','0','0000-00-00 00:00:00','0','1','class:component','0','{}','240','241','0','','1');
insert into `prp_menu` (`id`, `menutype`, `title`, `alias`, `note`, `path`, `link`, `type`, `published`, `parent_id`, `level`, `component_id`, `checked_out`, `checked_out_time`, `browserNav`, `access`, `img`, `template_style_id`, `params`, `lft`, `rgt`, `home`, `language`, `client_id`) values('417','main','COM_CATPROMOCIONAL_MMATRIZ_VARIABLES','com-catpromocional-mmatrizvariables','','com-catpromocional-mcatalogo/com-catpromocional-mmatrizvariables','index.php?option=com_catpromocional&view=catmtzvariables','component','1','410','2','10049','0','0000-00-00 00:00:00','0','1','class:component','0','{}','240','241','0','','1');
